version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/advent
      - elixir-deps:/advent/deps
      - elixir-build:/advent/_build
      - elixir-mix:/root/.mix
      - node_modules:/advent/assets/node_modules
    env_file:
      - ../.env
    environment:
      - MIX_ENV=dev
    command: sleep infinity
    dns:
      - 192.168.50.10 # Replace with your local DNS server if needed
      - 8.8.8.8       # Google Public DNS

volumes:
  elixir-deps:
  elixir-build:
  elixir-mix:
  node_modules:
